### ISSUE TITLE
ëtica y deontologia

### ISSUE THREAD

**Issue by FabianRicardoPerisset** [Tuple-Developers/Proyecto_Integrador#7]
[Todos los integrantes de la sociedad deberán estar matriculados ante el Consejo Profesional de Ciencias Informáticas de la Provincia de Córdoba.docx](https://github.com/user-attachments/files/15541771/Todos.los.integrantes.de.la.sociedad.deberan.estar.matriculados.ante.el.Consejo.Profesional.de.Ciencias.Informaticas.de.la.Provincia.de.Cordoba.docx)

**Comment by jmarchisone** [comment]
Completado en reunión de grupo, se carga final
